In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from gmr import GMM

from sklearn.mixture import GaussianMixture
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import f1_score, accuracy_score

from moebius.model.gmm.evol.optimizer import GMMOptimizer
from moebius.model.gmm.evol.parameters import EvolutionaryConfiguration
from moebius.model.gmm.evol.graph.graph import ProbabilisticGraphShuffler

from moebius.model.gmm.evol.graph.graph import GeneratorNode
from moebius.model.gmm.evol.operators.mutation import mutation, \
    Mutation, \
    ByNameNodeSelector, \
    RandomValueNodeMutator, \
    RandomDeltaNodeMutator, \
    ClapNodeDecoratedMutator, \
    RandomIndexRandomDeltaNodeMutator, \
    RandomValuesSumTo1NodeMutator, \
    DirichletValuesSumTo1NodeMutator

from moebius.model.gmm.evol.operators.crossover import crossover, \
    Crossover, \
    ExchangeFieldNodesCrossover, \
    RandomIndexExchangeFieldNodesCrossover

from moebius.model.gmm.evol.graph.initializer import GMMParametersInitializer, \
    RandomWeightsInitializer, \
    RandomMeansInitializer, \
    RandomCovariancesInitializer, \
    ConstantMeansInitializer, \
    ConstantCovariancesInitializer

from moebius.model.gmm.evol.graph.auto_initializer import AutoMeansInitializer

from moebius.model.gmm.bn import ContinuousBNSerializer, JsonDictSerializer, FilesystemStorage

from moebius.model.gmm.evol.bn import build_bn
from moebius.util import make_diagonal, print_gmm_params_fancy
from moebius import olr, olr_universal

/usr/local/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
def explode_cluster(data, target, clusters):
    indices_0_1 = [idx for idx, x in enumerate(target) if x in clusters]
    
    return (
        [list(data[idx]) for idx in indices_0_1],
        [target[idx].decode('UTF-8') if isinstance(target[idx], np.bytes_) else target[idx] for idx in indices_0_1]
    )

In [3]:
data = load_iris()
X = data['data']
y = data['target']

In [4]:
X_1_2, y_1_2 = explode_cluster(X, y, (1, 2))

In [5]:
gmm = GMM(n_components=2)
gmm.from_samples(np.array(X_1_2))

w = gmm.priors.tolist()
means = gmm.means.tolist()
cov = make_diagonal(gmm.covariances.tolist())

print_gmm_params_fancy(w, means, cov, decimal_places=3)

 ---  weights   --- 
[0.551 0.449]
 ---   means    --- 
[[6.545 2.949 5.48  1.985]
 [5.915 2.778 4.202 1.297]]
 --- covariance --- 
[[[0.387 0.092 0.303 0.062]
  [0.092 0.11  0.084 0.056]
  [0.303 0.084 0.328 0.075]
  [0.062 0.056 0.075 0.086]]

 [[0.275 0.097 0.185 0.054]
  [0.097 0.093 0.091 0.043]
  [0.185 0.091 0.201 0.061]
  [0.054 0.043 0.061 0.032]]]
 ---    OLR     --- 
0.3201848698063574


In [6]:
pd.DataFrame(data=X_1_2).describe()

0           1           2           3
count  100.000000  100.000000  100.000000  100.000000
mean     6.262000    2.872000    4.906000    1.676000
std      0.662834    0.332751    0.825578    0.424769
min      4.900000    2.000000    3.000000    1.000000
25%      5.800000    2.700000    4.375000    1.300000
50%      6.300000    2.900000    4.900000    1.600000
75%      6.700000    3.025000    5.525000    2.000000
max      7.900000    3.800000    6.900000    2.500000

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X_1_2, y_1_2, test_size=0.25, random_state=0)

In [8]:
model = LogisticRegression()
model.fit(X_train, y_train)

accuracy = accuracy_score(y_test, model.predict(X_test))
f1 = f1_score(y_test, model.predict(X_test), pos_label=2)
accuracy, f1

(0.92, 0.923076923076923)

In [9]:
auto = AutoMeansInitializer.from_data(X_1_2, 2)
auto.create_initial_means('Comp_3', 2)

[[1.2969685652784884], [1.9846085276174643]]

In [10]:
optimizer = GMMOptimizer(
    EvolutionaryConfiguration()
        .set_mutation_types([
            mutation(RandomValueNodeMutator('var', [
                [
                    [0.0, 0.25],
                ],
                [
                    [0.0, 0.25],
                ],
            ])),
            mutation(RandomValuesSumTo1NodeMutator('w')),
        ])
        .set_crossover_types([
            crossover(ExchangeFieldNodesCrossover('var')),
            crossover(RandomIndexExchangeFieldNodesCrossover('var'))
        ]),
    ProbabilisticGraphShuffler(0.5),
    GMMParametersInitializer(
        RandomWeightsInitializer(),
#         ConstantMeansInitializer({
#             'Comp_0': [
#                 [6.545],
#                 [5.915]
#             ],
#             'Comp_1': [
#                 [2.949],
#                 [2.778]
#             ],
#             'Comp_2': [
#                 [5.48],
#                 [4.202]
#             ],
#             'Comp_3': [
#                 [1.985],
#                 [1.297]
#             ]
#         }),
        AutoMeansInitializer.from_data(X_1_2, 2),
        RandomCovariancesInitializer(0, 2)
    )
)

In [11]:
optimization_result = optimizer.optimize(n_dim=4, n_comp=2, target_olr=0.3)

Generations:   0%|          | 1/500 [00:00<?, ?gen/s]

2024-04-14 12:57:56,667 - MultiprocessingDispatcher - Number of used CPU's: 6


 52%|█████▏    | 2585/5000 [00:00<00:00, 12931.01it/s]

2024-04-14 12:57:58,744 - MultiprocessingDispatcher - 1 individuals out of 1 in previous population were evaluated successfully.
2024-04-14 12:57:58,747 - EvoGraphOptimizer - Generation num: 1 size: 1
2024-04-14 12:57:58,747 - EvoGraphOptimizer - Best individuals: HallOfFame archive fitness (1): ['<custom=0.354>']


100%|██████████| 5000/5000 [00:00<00:00, 11018.83it/s]


2024-04-14 12:57:58,970 - EvoGraphOptimizer - Exceeded max number of attempts for extending initial graphs, stopping.Current size 1 instead of 10 graphs.
2024-04-14 12:57:58,971 - MultiprocessingDispatcher - Number of used CPU's: 6
2024-04-14 12:57:58,972 - MultiprocessingDispatcher - 1 individuals out of 1 in previous population were evaluated successfully.
2024-04-14 12:57:58,973 - EvoGraphOptimizer - Generation num: 2 size: 1
2024-04-14 12:57:58,973 - EvoGraphOptimizer - Best individuals: HallOfFame archive fitness (1): ['<custom=0.354>']
2024-04-14 12:57:58,974 - EvoGraphOptimizer - no improvements for 1 iterations
2024-04-14 12:57:58,974 - EvoGraphOptimizer - spent time: 0.0 min
2024-04-14 12:57:58,975 - EvoGraphOptimizer - Next population size: 20; max graph depth: 100
2024-04-14 12:57:58,980 - MultiprocessingDispatcher - Number of used CPU's: 6


 76%|███████▌  | 3793/5000 [00:00<00:00, 12673.62it/s]

Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6011'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6011'


100%|██████████| 5000/5000 [00:00<00:00, 12503.87it/s]


2024-04-14 12:58:02,263 - MultiprocessingDispatcher - 18 individuals out of 20 in previous population were evaluated successfully.
2024-04-14 12:58:02,264 - EvoGraphOptimizer - Generation num: 3 size: 19
2024-04-14 12:58:02,264 - EvoGraphOptimizer - Best individuals: HallOfFame archive fitness (1): ['<custom=0.116>']
2024-04-14 12:58:02,264 - EvoGraphOptimizer - Next population size: 38; max graph depth: 100
2024-04-14 12:58:02,272 - MultiprocessingDispatcher - Number of used CPU's: 6


  0%|          | 0/5000 [00:00<?, ?it/s]

Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6025'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6026'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6025'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6027'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6025'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6027'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6029'


100%|██████████| 5000/5000 [00:00<00:00, 12432.47it/s]


2024-04-14 12:58:03,603 - MultiprocessingDispatcher - 11 individuals out of 18 in previous population were evaluated successfully.
2024-04-14 12:58:03,604 - EvoGraphOptimizer - Generation num: 4 size: 29
2024-04-14 12:58:03,605 - EvoGraphOptimizer - Best individuals: HallOfFame archive fitness (1): ['<custom=0.116>']
2024-04-14 12:58:03,605 - EvoGraphOptimizer - no improvements for 1 iterations
2024-04-14 12:58:03,606 - EvoGraphOptimizer - spent time: 0.1 min
2024-04-14 12:58:03,606 - EvoGraphOptimizer - Next population size: 55; max graph depth: 100
2024-04-14 12:58:03,700 - MultiprocessingDispatcher - Number of used CPU's: 6
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6036'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6036'


 48%|████▊     | 2384/5000 [00:00<00:00, 11816.37it/s]

Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6036'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6038'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6036'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6038'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6039'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6036'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6038'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6039'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6040'


100%|██████████| 5000/5000 [00:00<00:00, 12587.78it/s]


2024-04-14 12:58:05,679 - MultiprocessingDispatcher - 17 individuals out of 28 in previous population were evaluated successfully.
2024-04-14 12:58:05,680 - EvoGraphOptimizer - Generation num: 5 size: 45
2024-04-14 12:58:05,681 - EvoGraphOptimizer - Best individuals: HallOfFame archive fitness (1): ['<custom=0.023>']
2024-04-14 12:58:05,681 - EvoGraphOptimizer - Next population size: 55; max graph depth: 100
2024-04-14 12:58:05,699 - MultiprocessingDispatcher - Number of used CPU's: 6


100%|██████████| 5000/5000 [00:00<00:00, 11877.44it/s]


Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6053'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6053'


 49%|████▉     | 2460/5000 [00:00<00:00, 12335.33it/s]

Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6053'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6054'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6053'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6055'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6053'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6055'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6057'


  0%|          | 0/5000 [00:00<?, ?it/s]

Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6078'


100%|██████████| 5000/5000 [00:00<00:00, 11954.12it/s]


2024-04-14 12:58:09,368 - MultiprocessingDispatcher - 34 individuals out of 44 in previous population were evaluated successfully.
2024-04-14 12:58:09,371 - EvoGraphOptimizer - Generation num: 6 size: 55
2024-04-14 12:58:09,372 - EvoGraphOptimizer - Best individuals: HallOfFame archive fitness (1): ['<custom=0.005>']
2024-04-14 12:58:09,372 - EvoGraphOptimizer - Next population size: 55; max graph depth: 100
2024-04-14 12:58:09,394 - MultiprocessingDispatcher - Number of used CPU's: 6
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6087'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6087'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6087'


 48%|████▊     | 2392/5000 [00:00<00:00, 11920.98it/s]

Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6087'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6090'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6087'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6090'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6091'


 72%|███████▏  | 3604/5000 [00:00<00:00, 12052.86it/s]

Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6113'


100%|██████████| 5000/5000 [00:00<00:00, 12341.00it/s]


2024-04-14 12:58:14,286 - MultiprocessingDispatcher - 45 individuals out of 54 in previous population were evaluated successfully.
2024-04-14 12:58:14,289 - EvoGraphOptimizer - Generation num: 7 size: 55
2024-04-14 12:58:14,290 - EvoGraphOptimizer - Best individuals: HallOfFame archive fitness (1): ['<custom=0.002>']
2024-04-14 12:58:14,290 - EvoGraphOptimizer - Next population size: 55; max graph depth: 100
2024-04-14 12:58:14,315 - MultiprocessingDispatcher - Number of used CPU's: 6


100%|██████████| 5000/5000 [00:00<00:00, 12133.99it/s]


Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6132'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6132'


 48%|████▊     | 2418/5000 [00:00<00:00, 12050.17it/s]

Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6132'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6133'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6132'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6134'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6132'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6134'


 48%|████▊     | 2390/5000 [00:00<00:00, 11951.23it/s]

Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6141'


 26%|██▌       | 1286/5000 [00:00<00:00, 12852.99it/s]

Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6146'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6148'


100%|██████████| 5000/5000 [00:00<00:00, 11736.99it/s]


2024-04-14 12:58:18,965 - MultiprocessingDispatcher - 43 individuals out of 54 in previous population were evaluated successfully.
2024-04-14 12:58:18,969 - EvoGraphOptimizer - Generation num: 8 size: 55
2024-04-14 12:58:18,969 - EvoGraphOptimizer - Best individuals: HallOfFame archive fitness (1): ['<custom=0.002>']
2024-04-14 12:58:18,970 - EvoGraphOptimizer - no improvements for 1 iterations
2024-04-14 12:58:18,970 - EvoGraphOptimizer - spent time: 0.4 min
2024-04-14 12:58:18,971 - EvoGraphOptimizer - Next population size: 55; max graph depth: 100
2024-04-14 12:58:18,997 - MultiprocessingDispatcher - Number of used CPU's: 6
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6175'


 47%|████▋     | 2366/5000 [00:00<00:00, 11829.92it/s]

Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6175'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6176'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6175'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6176'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6175'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6176'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6178'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6175'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6176'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6178'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6179'


 73%|███████▎  | 3636/5000 [00:00<00:00, 12160.42it/s]

Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6183'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6184'


100%|██████████| 5000/5000 [00:00<00:00, 11795.64it/s]


2024-04-14 12:58:23,533 - MultiprocessingDispatcher - 40 individuals out of 54 in previous population were evaluated successfully.
2024-04-14 12:58:23,537 - EvoGraphOptimizer - Generation num: 9 size: 55
2024-04-14 12:58:23,537 - EvoGraphOptimizer - Best individuals: HallOfFame archive fitness (1): ['<custom=0.001>']
2024-04-14 12:58:23,537 - EvoGraphOptimizer - Next population size: 55; max graph depth: 100
2024-04-14 12:58:23,560 - MultiprocessingDispatcher - Number of used CPU's: 6
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6215'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6216'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6216'


 51%|█████▏    | 2570/5000 [00:00<00:00, 12829.16it/s]

Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6215'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6218'


 72%|███████▏  | 3593/5000 [00:00<00:00, 12002.00it/s]

Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6255'


100%|██████████| 5000/5000 [00:00<00:00, 11819.58it/s]


2024-04-14 12:58:28,637 - MultiprocessingDispatcher - 48 individuals out of 54 in previous population were evaluated successfully.
2024-04-14 12:58:28,641 - EvoGraphOptimizer - Generation num: 10 size: 55
2024-04-14 12:58:28,641 - EvoGraphOptimizer - Best individuals: HallOfFame archive fitness (1): ['<custom=0.000>']
2024-04-14 12:58:28,642 - EvoGraphOptimizer - Next population size: 55; max graph depth: 100
2024-04-14 12:58:28,665 - MultiprocessingDispatcher - Number of used CPU's: 6
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6263'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6263'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6263'


 24%|██▍       | 1201/5000 [00:00<00:00, 12000.66it/s]

Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6263'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6266'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6263'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6266'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6267'


 51%|█████     | 2538/5000 [00:00<00:00, 12715.12it/s]

Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6303'


 70%|███████   | 3517/5000 [00:00<00:00, 11676.53it/s]

2024-04-14 12:58:33,745 - MultiprocessingDispatcher - 45 individuals out of 54 in previous population were evaluated successfully.
2024-04-14 12:58:33,749 - EvoGraphOptimizer - Generation num: 11 size: 55
2024-04-14 12:58:33,749 - EvoGraphOptimizer - Best individuals: HallOfFame archive fitness (1): ['<custom=0.000>']
2024-04-14 12:58:33,749 - EvoGraphOptimizer - no improvements for 1 iterations
2024-04-14 12:58:33,750 - EvoGraphOptimizer - spent time: 0.6 min
2024-04-14 12:58:33,750 - EvoGraphOptimizer - Next population size: 55; max graph depth: 100
2024-04-14 12:58:33,775 - MultiprocessingDispatcher - Number of used CPU's: 6


100%|██████████| 5000/5000 [00:00<00:00, 11779.22it/s]


Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6308'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6308'


 47%|████▋     | 2334/5000 [00:00<00:00, 11694.82it/s]

Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6308'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6309'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6308'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6310'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6308'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6310'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6312'


 48%|████▊     | 2406/5000 [00:00<00:00, 12060.36it/s]

Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6334'


 97%|█████████▋| 4856/5000 [00:00<00:00, 12225.38it/s]

2024-04-14 12:58:38,706 - MultiprocessingDispatcher - 44 individuals out of 54 in previous population were evaluated successfully.
2024-04-14 12:58:38,710 - EvoGraphOptimizer - Generation num: 12 size: 55
2024-04-14 12:58:38,710 - EvoGraphOptimizer - Best individuals: HallOfFame archive fitness (1): ['<custom=0.000>']
2024-04-14 12:58:38,711 - EvoGraphOptimizer - Next population size: 55; max graph depth: 100


100%|██████████| 5000/5000 [00:00<00:00, 11928.86it/s]


2024-04-14 12:58:38,734 - MultiprocessingDispatcher - Number of used CPU's: 6
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6353'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6352'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6352'


 48%|████▊     | 2400/5000 [00:00<00:00, 12050.65it/s]

Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6352'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6356'


 48%|████▊     | 2402/5000 [00:00<00:00, 12018.76it/s]

Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6365'


100%|██████████| 5000/5000 [00:00<00:00, 11948.56it/s]


2024-04-14 12:58:43,885 - MultiprocessingDispatcher - 48 individuals out of 54 in previous population were evaluated successfully.
2024-04-14 12:58:43,889 - EvoGraphOptimizer - Generation num: 13 size: 55
2024-04-14 12:58:43,889 - EvoGraphOptimizer - Best individuals: HallOfFame archive fitness (1): ['<custom=0.000>']
2024-04-14 12:58:43,890 - EvoGraphOptimizer - no improvements for 1 iterations
2024-04-14 12:58:43,890 - EvoGraphOptimizer - spent time: 0.8 min
2024-04-14 12:58:43,891 - EvoGraphOptimizer - Next population size: 55; max graph depth: 100
2024-04-14 12:58:43,912 - MultiprocessingDispatcher - Number of used CPU's: 6
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6400'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6400'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6400'


 23%|██▎       | 1174/5000 [00:00<00:00, 11737.74it/s]

Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6400'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6402'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6400'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6402'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6404'


100%|██████████| 5000/5000 [00:00<00:00, 11813.33it/s]


2024-04-14 12:58:48,977 - MultiprocessingDispatcher - 46 individuals out of 54 in previous population were evaluated successfully.
2024-04-14 12:58:48,980 - EvoGraphOptimizer - Generation num: 14 size: 55
2024-04-14 12:58:48,981 - EvoGraphOptimizer - Best individuals: HallOfFame archive fitness (1): ['<custom=0.000>']
2024-04-14 12:58:48,981 - EvoGraphOptimizer - Next population size: 55; max graph depth: 100


100%|██████████| 5000/5000 [00:00<00:00, 11763.54it/s]


2024-04-14 12:58:49,005 - MultiprocessingDispatcher - Number of used CPU's: 6
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6446'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6446'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6446'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6446'


 49%|████▉     | 2452/5000 [00:00<00:00, 12288.27it/s]

Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6446'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6449'


 72%|███████▏  | 3596/5000 [00:00<00:00, 12044.59it/s]

Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6453'


 47%|████▋     | 2359/5000 [00:00<00:00, 11811.30it/s]

Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6462'


 96%|█████████▋| 4823/5000 [00:00<00:00, 12146.82it/s]

2024-04-14 12:58:54,280 - MultiprocessingDispatcher - 46 individuals out of 54 in previous population were evaluated successfully.
2024-04-14 12:58:54,284 - EvoGraphOptimizer - Generation num: 15 size: 55
2024-04-14 12:58:54,285 - EvoGraphOptimizer - Best individuals: HallOfFame archive fitness (1): ['<custom=0.000>']
2024-04-14 12:58:54,285 - EvoGraphOptimizer - Next population size: 55; max graph depth: 100


100%|██████████| 5000/5000 [00:00<00:00, 12049.05it/s]


2024-04-14 12:58:54,310 - MultiprocessingDispatcher - Number of used CPU's: 6
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6492'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6492'


 47%|████▋     | 2372/5000 [00:00<00:00, 11896.60it/s]

Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6492'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6493'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6492'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6494'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6492'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6494'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6495'


 24%|██▍       | 1222/5000 [00:00<00:00, 12215.96it/s]

Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6518'


 24%|██▍       | 1213/5000 [00:00<00:00, 12123.83it/s]

Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6522'


 94%|█████████▎| 4687/5000 [00:00<00:00, 11690.73it/s]

Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6525'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6526'


100%|██████████| 5000/5000 [00:00<00:00, 11991.27it/s]


2024-04-14 12:58:58,979 - MultiprocessingDispatcher - 41 individuals out of 54 in previous population were evaluated successfully.
2024-04-14 12:58:58,982 - EvoGraphOptimizer - Generation num: 16 size: 55
2024-04-14 12:58:58,983 - EvoGraphOptimizer - Best individuals: HallOfFame archive fitness (1): ['<custom=0.000>']
2024-04-14 12:58:58,983 - EvoGraphOptimizer - no improvements for 1 iterations
2024-04-14 12:58:58,983 - EvoGraphOptimizer - spent time: 1.0 min
2024-04-14 12:58:58,984 - EvoGraphOptimizer - Next population size: 55; max graph depth: 100
2024-04-14 12:58:59,006 - MultiprocessingDispatcher - Number of used CPU's: 6


100%|██████████| 5000/5000 [00:00<00:00, 11890.90it/s]


Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6533'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6533'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6533'


 47%|████▋     | 2356/5000 [00:00<00:00, 11713.28it/s]

Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6533'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6536'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6533'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6536'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6537'


 48%|████▊     | 2381/5000 [00:00<00:00, 11912.22it/s]

Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6565'


100%|██████████| 5000/5000 [00:00<00:00, 11768.62it/s]


2024-04-14 12:59:04,186 - MultiprocessingDispatcher - 45 individuals out of 54 in previous population were evaluated successfully.
2024-04-14 12:59:04,189 - EvoGraphOptimizer - Generation num: 17 size: 55
2024-04-14 12:59:04,189 - EvoGraphOptimizer - Best individuals: HallOfFame archive fitness (1): ['<custom=0.000>']
2024-04-14 12:59:04,190 - EvoGraphOptimizer - no improvements for 2 iterations
2024-04-14 12:59:04,190 - EvoGraphOptimizer - spent time: 1.1 min
2024-04-14 12:59:04,191 - EvoGraphOptimizer - Next population size: 55; max graph depth: 100
2024-04-14 12:59:04,214 - MultiprocessingDispatcher - Number of used CPU's: 6
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6578'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6578'


 23%|██▎       | 1141/5000 [00:00<00:00, 11407.97it/s]

Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6578'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6580'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6578'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6580'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6578'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6580'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6582'


100%|██████████| 5000/5000 [00:00<00:00, 11817.04it/s]


2024-04-14 12:59:09,505 - MultiprocessingDispatcher - 45 individuals out of 54 in previous population were evaluated successfully.
2024-04-14 12:59:09,509 - EvoGraphOptimizer - Generation num: 18 size: 55
2024-04-14 12:59:09,509 - EvoGraphOptimizer - Best individuals: HallOfFame archive fitness (1): ['<custom=0.000>']
2024-04-14 12:59:09,509 - EvoGraphOptimizer - no improvements for 3 iterations
2024-04-14 12:59:09,510 - EvoGraphOptimizer - spent time: 1.2 min
2024-04-14 12:59:09,510 - EvoGraphOptimizer - Next population size: 55; max graph depth: 100
2024-04-14 12:59:09,533 - MultiprocessingDispatcher - Number of used CPU's: 6


 46%|████▋     | 2324/5000 [00:00<00:00, 11636.03it/s]

Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6623'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6623'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6623'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6625'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6623'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6625'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6623'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6625'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6627'


 47%|████▋     | 2340/5000 [00:00<00:00, 11742.17it/s]

Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6630'


 46%|████▋     | 2315/5000 [00:00<00:00, 11602.39it/s]

Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6637'


100%|██████████| 5000/5000 [00:00<00:00, 12052.41it/s]


2024-04-14 12:59:14,700 - MultiprocessingDispatcher - 43 individuals out of 54 in previous population were evaluated successfully.
2024-04-14 12:59:14,704 - EvoGraphOptimizer - Generation num: 19 size: 55
2024-04-14 12:59:14,704 - EvoGraphOptimizer - Best individuals: HallOfFame archive fitness (1): ['<custom=0.000>']
2024-04-14 12:59:14,705 - EvoGraphOptimizer - Next population size: 55; max graph depth: 100
2024-04-14 12:59:14,730 - MultiprocessingDispatcher - Number of used CPU's: 6
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6666'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6666'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6666'


 48%|████▊     | 2402/5000 [00:00<00:00, 11957.29it/s]

Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6666'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6669'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6666'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6669'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6670'


 71%|███████   | 3549/5000 [00:00<00:00, 11736.80it/s]

Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6698'


 49%|████▉     | 2450/5000 [00:00<00:00, 12173.34it/s]

Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6706'


100%|██████████| 5000/5000 [00:00<00:00, 12147.97it/s]


2024-04-14 12:59:19,996 - MultiprocessingDispatcher - 44 individuals out of 54 in previous population were evaluated successfully.
2024-04-14 12:59:20,000 - EvoGraphOptimizer - Generation num: 20 size: 55
2024-04-14 12:59:20,000 - EvoGraphOptimizer - Best individuals: HallOfFame archive fitness (1): ['<custom=0.000>']
2024-04-14 12:59:20,001 - EvoGraphOptimizer - no improvements for 1 iterations
2024-04-14 12:59:20,001 - EvoGraphOptimizer - spent time: 1.4 min
2024-04-14 12:59:20,002 - EvoGraphOptimizer - Next population size: 55; max graph depth: 100
2024-04-14 12:59:20,026 - MultiprocessingDispatcher - Number of used CPU's: 6
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6710'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6710'


 47%|████▋     | 2330/5000 [00:00<00:00, 11675.64it/s]

Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6710'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6711'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6710'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6712'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6710'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6712'


 48%|████▊     | 2383/5000 [00:00<00:00, 11906.74it/s]

Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6722'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6723'


100%|██████████| 5000/5000 [00:00<00:00, 12211.65it/s]


2024-04-14 12:59:25,334 - MultiprocessingDispatcher - 44 individuals out of 54 in previous population were evaluated successfully.
2024-04-14 12:59:25,338 - EvoGraphOptimizer - Generation num: 21 size: 55
2024-04-14 12:59:25,339 - EvoGraphOptimizer - Best individuals: HallOfFame archive fitness (1): ['<custom=0.000>']
2024-04-14 12:59:25,339 - EvoGraphOptimizer - no improvements for 2 iterations
2024-04-14 12:59:25,340 - EvoGraphOptimizer - spent time: 1.5 min
2024-04-14 12:59:25,340 - EvoGraphOptimizer - Next population size: 55; max graph depth: 100
2024-04-14 12:59:25,363 - MultiprocessingDispatcher - Number of used CPU's: 6
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6754'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6754'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6754'


 50%|█████     | 2506/5000 [00:00<00:00, 12466.85it/s]

Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6754'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6756'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6754'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6756'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6758'


100%|██████████| 5000/5000 [00:00<00:00, 11771.86it/s]


2024-04-14 12:59:30,723 - MultiprocessingDispatcher - 46 individuals out of 54 in previous population were evaluated successfully.
2024-04-14 12:59:30,727 - EvoGraphOptimizer - Generation num: 22 size: 55
2024-04-14 12:59:30,727 - EvoGraphOptimizer - Best individuals: HallOfFame archive fitness (1): ['<custom=0.000>']
2024-04-14 12:59:30,728 - EvoGraphOptimizer - no improvements for 3 iterations
2024-04-14 12:59:30,728 - EvoGraphOptimizer - spent time: 1.6 min
2024-04-14 12:59:30,729 - EvoGraphOptimizer - Next population size: 55; max graph depth: 100
2024-04-14 12:59:30,755 - MultiprocessingDispatcher - Number of used CPU's: 6
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6800'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6800'


 47%|████▋     | 2327/5000 [00:00<00:00, 11692.39it/s]

Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6800'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6801'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6800'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6802'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6800'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6802'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6804'


 49%|████▊     | 2436/5000 [00:00<00:00, 12027.42it/s]

Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6821'


 97%|█████████▋| 4848/5000 [00:00<00:00, 12160.19it/s]

2024-04-14 12:59:35,953 - MultiprocessingDispatcher - 44 individuals out of 54 in previous population were evaluated successfully.
2024-04-14 12:59:35,957 - EvoGraphOptimizer - Generation num: 23 size: 55
2024-04-14 12:59:35,957 - EvoGraphOptimizer - Best individuals: HallOfFame archive fitness (1): ['<custom=0.000>']
2024-04-14 12:59:35,957 - EvoGraphOptimizer - no improvements for 4 iterations
2024-04-14 12:59:35,958 - EvoGraphOptimizer - spent time: 1.7 min
2024-04-14 12:59:35,958 - EvoGraphOptimizer - Next population size: 55; max graph depth: 100
2024-04-14 12:59:35,984 - MultiprocessingDispatcher - Number of used CPU's: 6


100%|██████████| 5000/5000 [00:00<00:00, 12064.46it/s]


Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6844'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6844'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6844'


 24%|██▎       | 1176/5000 [00:00<00:00, 11751.16it/s]

Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6844'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6847'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6844'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6847'
Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6848'


  0%|          | 0/5000 [00:00<?, ?it/s] 12304.41it/s]

Error message
[Errno 17] File exists: '/root/BAMT/Nodes_data/6870'


 96%|█████████▌| 4783/5000 [00:00<00:00, 11958.18it/s]

2024-04-14 12:59:41,211 - MultiprocessingDispatcher - 45 individuals out of 54 in previous population were evaluated successfully.
2024-04-14 12:59:41,214 - EvoGraphOptimizer - Generation num: 24 size: 55
2024-04-14 12:59:41,215 - EvoGraphOptimizer - Best individuals: HallOfFame archive fitness (1): ['<custom=0.000>']
2024-04-14 12:59:41,215 - EvoGraphOptimizer - no improvements for 5 iterations
2024-04-14 12:59:41,216 - EvoGraphOptimizer - spent time: 1.7 min
2024-04-14 12:59:41,216 - GroupedCondition - Optimisation finished: Early stopping iterations criteria was satisfied


Generations:   0%|          | 1/500 [01:44<?, ?gen/s]

2024-04-14 12:59:41,217 - OptimisationTimer - Composition time: 1.743 min
2024-04-14 12:59:41,217 - EvoGraphOptimizer - Generation num: 25 size: 1
2024-04-14 12:59:41,218 - EvoGraphOptimizer - Best individuals: HallOfFame archive fitness (1): ['<custom=0.000>']
2024-04-14 12:59:41,219 - EvoGraphOptimizer - no improvements for 6 iterations
2024-04-14 12:59:41,219 - EvoGraphOptimizer - spent time: 1.7 min


In [12]:
optimized_graph = optimization_result[0]
net = build_bn(optimized_graph)

In [13]:
data = net.sample(200)

100%|██████████| 200/200 [00:00<00:00, 807.84it/s]


In [14]:
data.describe()

Comp_0      Comp_1      Comp_2      Comp_3
count  200.000000  200.000000  200.000000  200.000000
mean     6.238868    2.906282    5.141847    2.058017
std      0.487391    0.208641    0.647394    1.395904
min      4.937032    2.146774    3.521673   -1.224117
25%      5.883381    2.787700    4.690504    1.109719
50%      6.285163    2.918602    5.374628    1.964388
75%      6.557211    3.039409    5.620151    2.965573
max      7.342145    3.573231    6.161262    5.593079

In [15]:
gmm = GMM(n_components=2)
gmm.from_samples(data.to_numpy())

w = gmm.priors.tolist()
means = gmm.means.tolist()
cov = make_diagonal(gmm.covariances.tolist())

# print_gmm_params_fancy(w, means, cov, decimal_places=3)

olr_universal(w, means, cov)

0.29827803905987227

In [16]:
net

In [16]:
serialized = ContinuousBNSerializer().serialize(net)
j = JsonDictSerializer().serialize(serialized)
FilesystemStorage().write(j, './bns_iris/0.3_1.json')

In [17]:
gmm = GaussianMixture(n_components = 2) 
gmm.fit(data)
        
sample = gmm.sample(200)
data = sample[0]
labels = [2 if each == 1 else 1 for each in sample[1]]

accuracy = accuracy_score(labels, model.predict(data))
f1 = f1_score(labels, model.predict(data))

accuracy, f1

(0.93, 0.933477021642587)